### ISSUE TITLE
Enabling the cleanup module breaks things

### ISSUE THREAD

**Issue by cpatrick** [midasplatform/Midas#80]
This results in an error as reported on the mailing list:

```
The system has encountered the following error:
Uncaught exception 'Zend_Exception' with message 'Task already exits' in /home/midas/pacs/notification/MIDASNotifier.php:93 Stack trace: #0 /home/midas/pacs/core/AppController.php(226): MIDAS_Notifier->__construct(true, Object(Zend_Session_Namespace)) #1 /home/midas/pacs/library/Zend/Controller/Action.php(502): AppController->preDispatch() #2 /home/midas/pacs/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('errorAction') #3 /home/midas/pacs/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #4 /home/midas/pacs/library/Zend/Application/Bootstrap/Bootstrap.php(101): Zend_Controller_Front->dispatch() #5 /home/midas/pacs/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run() #6 /home/midas/pacs/index.php(63): Zend_Application->run() #7 {main} Next exception 'Zend_Controller_Exception' with message 'Task already exits#0 /home/midas/pacs/core
In /home/midas/pacs/library/Zend/Controller/Plugin/Broker.php, line: 336
At 18:03:28 2014-12-01
Please notify your administrator with this information.
```

**Comment by jamiesnape** [comment]
Fix now merged into master. If someone can test it, I will close the issue.
